export interface InvoiceRecord {
  id: string;
  invoiceNo: string;
  companyId?: string | null;
  siteId?: string | null;
  company_id?: string | null;
  site_id?: string | null;
  date: string;
  invoice_date?: string;
  monthYear: string;
  billing_period?: string;
  clientName: string;
  siteName: string;
  amount: number;
  sub_total?: number;
  tax_total?: number;
  grand_total?: number;
  type: 'Tax Invoice' | 'Proforma Invoice' | string;
  status: 'Paid' | 'Pending' | 'Draft' | 'Overdue' | string;
  itemsCount: number;
  line_items?: any[];
  challan_no?: string;
  challan_date?: string;
  buyer_order_no?: string;
  dispatch_doc_no?: string;
  dispatched_through?: string;
  destination?: string;
  terms_of_delivery?: string;
  machinery_charges?: number;
  machineryCharges?: number;
  material_charges?: number;
  materialCharges?: number;
  additional_charges?: any[];
  additionalCharges?: any[];
  is_material?: boolean;
  is_locked?: boolean | null;
  isLocked?: boolean | null;
  sites?: {

    client_name?: string;
    site_name?: string;
  };
  companies?: {
    name?: string;
    legal_name?: string;
  };
  payload?: any;
  storage_provider?: string | null;
  storage_key?: string | null;
  invoice_storage_provider?: string | null;
  certified_doc_storage_key?: string | null;
  generated_pdf_storage_key?: string | null;
  certified_attendance_storage_key?: string | null;
  view_url?: string | null;
  certified_doc_view_url?: string | null;
  generated_pdf_view_url?: string | null;
  certified_attendance_view_url?: string | null;
  certified_doc_url?: string | null;
  certifiedDocUrl?: string | null;
  certified_attendance_url?: string | null;
  certifiedAttendanceUrl?: string | null;
  generated_pdf_url?: string | null;
  generatedPdfUrl?: string | null;
  cancelled_at?: string | null;
  cancelledAt?: string | null;
  cancelled_reason?: string | null;
  cancelledReason?: string | null;
  approved_at?: string | null;
  approvedAt?: string | null;
  certified_doc_confirmed_at?: string | null;
  certifiedDocConfirmedAt?: string | null;
  certified_attendance_confirmed_at?: string | null;
  certifiedAttendanceConfirmedAt?: string | null;
  previous_version_id?: string | null;
  created_at?: string;
  updated_at?: string;
}

export type CreateInvoiceDTO = Partial<InvoiceRecord> & any;
