export interface CompanyProfile {
  id: string;
  code: string;
  entity_code?: string;
  name: string;
  legal_name: string;
  tagline?: string;
  gstin?: string;
  pan?: string;
  cin?: string;
  cin_no?: string;
  email?: string;
  email_website?: string;
  phone?: string;
  contact_no?: string;
  website?: string;
  address_line1: string;
  address_line2?: string;
  city?: string;
  state?: string;
  pincode?: string;
  state_code?: string;
  bank_name: string;
  bank_account_no: string;
  account_no?: string;
  bank_ifsc: string;
  ifsc_code?: string;
  bank_branch: string;
  branch_name?: string;
  upi_id?: string;
  terms_and_conditions: string[];
  default_terms?: string[];
  tax_prefix?: string;
  tax_sequence?: number;
  proforma_prefix?: string;
  proforma_sequence?: number;
  logo_url?: string;
  stamp_url?: string;
  signature_url?: string;
  is_active: boolean;
  is_locked?: boolean;
  created_at: string;
  updated_at: string;
}

export type CreateCompanyInput = Omit<CompanyProfile, 'id' | 'created_at' | 'updated_at' | 'is_active'>;
export type UpdateCompanyInput = Partial<CreateCompanyInput>;
